language: node_js
sudo: required
dist: trusty
addons:
    chrome: stable
node_js:
- 8
env:
  global:
  - NODE_ENV=production
  - NPM_TAG=latest
cache:
  directories:
  - node_modules
install:
- npm --production=false install
- npm --production=false update
script:
- npm test
before_deploy:
- >
  if [ -z "$BEFORE_DEPLOY_RAN" ]; then
    npm --no-git-tag-version version 0.1.0-prerelease.$(date +%Y%m%d%H%M%S)
    if [ "$TRAVIS_BRANCH" == "develop" ]; then export NPM_TAG=develop; fi
    git config --global user.email $(git log --pretty=format:"%ae" -n1)
    git config --global user.name $(git log --pretty=format:"%an" -n1)
    export BEFORE_DEPLOY_RAN=true
  fi
deploy:
- provider: script
  on:
    branch:
      - fabricat
    condition: $TRAVIS_EVENT_TYPE != cron
  skip_cleanup: true
  script: npm run deploy -- -x -e $TRAVIS_BRANCH -r https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
- provider: script
  on:
    branch:
      - fabricat
    condition: $TRAVIS_EVENT_TYPE != cron
  script: npm run prune -- https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  